In [1]:
import pandas as pd
import numpy as np

df_geneData = pd.read_excel('stepDataPrep_40_3_1.xlsx', header = 0)
df_geneData.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54449 entries, 0 to 54448
Data columns (total 4 columns):
Variable1    54449 non-null object
Variable2    54449 non-null object
Variable3    54449 non-null object
Output       54449 non-null int64
dtypes: int64(1), object(3)
memory usage: 1.7+ MB


In [20]:
df_geneDataSelect = df_geneData.head(30000)
df_geneDataSelect

Variable1  \
0      4411131312233231442413431114231123332133   
1      4433443312233444243434141124214431113221   
2      1433143422433441422121333244444422121432   
3      1441133424431444324433343242332321423321   
4      4223433112424332132134323433142442422323   
5      2122211223444234224231443334311231311341   
6      2132232122223234322322142343221423211422   
7      3113132432232243433233233444221323421233   
8      2231323211234221334231133232324311321212   
9      3343323312112242113214332412112223243442   
10     1133423424122432144233132324423423233121   
11     4221344244232223411331323242221331131344   
12     2443311313233243111422232442332433332243   
13     2232123143233234424421423222132321422344   
14     4314223231342324311331224324332224321331   
15     3234423234423343323234223232213343322143   
16     2123224342341131423242112441333114223123   
17     2144421221442112323113222434431112232432   
18     4342324312233412231224231334231324334233   
19     3222132314343243142312142234342311313213   
20     2223344232431124421321423222131321132432   
21     1233433232224323242234232212231433321223   
22     1243323232243242122313213314332313342332   
23     3124123132343432432232343323323121112433   
24     4321324342211233424324311314221332311211   
25     2243242312343243334343142334122311213342   
26     1432322424114212324311434222431222323444   
27     3233211312213234324231132314221224324333   
28     3143443322114332141322132114242333144422   
29     4432112431421142233121324442322442423133   
...                                         ...   
29970  1131431224331221414224233224331342233232   
29971  3222322423222311122243323442332211243112   
29972  2433221322133233333131422424222323123131   
29973  4311331211422423231122334223314211312434   
29974  3322243332442322322323142442343342312214   
29975  1132433222232433142133223312322432322132   
29976  2324224231211311224424334234323231331244   
29977  3412122341243322414142243242332323243342   
29978  3323122444214232321232321424422332324223   
29979  1232334442221431324323212322314242223224   
29980  4332311243313311143342422311243242122412   
29981  3421222423133223133223223321421244323131   
29982  4223221232321442123234231314232224324231   
29983  2442423232243312314132232312232132124332   
29984  3323323244234422322431224333232322232124   
29985  2441243221334324221434422323211432142422   
29986  1241233231334214231241224321121321414223   
29987  2332412322312342311232133132112322132313   
29988  2232423121322222432133121322432323134424   
29989  3224322433231221214322331424344231231223   
29990  2112243332412321243242332323322142311232   
29991  2121232331233112132142323222323324123323   
29992  4344232231233223341211331223321344324323   
29993  3442243123422432332123223222242311112322   
29994  1423421431321144223223223223321322421224   
29995  2213142232333224332134122113222214331423   
29996  2332312213232343313243243232114322323332   
29997  1322143342132312131422433424322322322123   
29998  4242233211433233321213241224231433224342   
29999  3312132323214323342243322332132332213332   

                                      Variable2  \
0      4211444221122132312212341141314131412133   
1      4413333233321444222143332111133443423131   
2      2314212213331434122222132332121133344142   
3      4343314113422332221412332412114133232442   
4      1431324322342221121144211212243314223422   
5      2242334232242243311243242334311232332313   
6      2123433232222232242233423212232232243232   
7      2231242241231332331131122313214231422324   
8      2132412243112232122442122442313112442342   
9      2424143343333423322433321131222122431432   
10     4334211332224321324211232214211231144211   
11     2442212122442112322244242311332332213213   
12     1233433223423132232233112433111222343423   
13     2211234323231124331133232324311323334314   
14     2113243342132142312112142213232122342322   
15     3232424221133132431221122121322432233131   
16     2

In [21]:
input_X = df_geneDataSelect[['Variable1','Variable2','Variable3',]]
output_y = df_geneDataSelect['Output']

In [22]:
from sklearn.cross_validation import train_test_split

X_train, X_test, y_train, y_test = train_test_split(input_X, output_y, test_size=0.25, random_state=33)





In [23]:
from sklearn import tree

clf = tree.DecisionTreeClassifier(criterion = 'entropy', max_depth = 3, min_samples_leaf = 5)
clf = clf.fit(X_train, y_train)

ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

In [24]:
from sklearn import metrics

def measure_performance(X, y, clf, show_accuracy=True, show_classification_report=True, show_confusion_matrix=True):
    y_pred = clf.predict(X)
    if show_accuracy:
        print("Accuracy:{0:.3f}".format(metrics.accuracy_score(y, y_pred)),"\n")

    if show_classification_report:
        print("Classification report")
        print(metrics.classification_report(y,y_pred),"\n")

    if show_confusion_matrix:
        print("Confusion matrix")
        print(metrics.confusion_matrix(y,y_pred),"\n")
        
# And call this method for the training data (display only accuracy)
measure_performance(X_test, y_test, clf) #show_classification_report=False, show_confusion_matrix=False)




NotFittedError: Estimator not fitted, call `fit` before exploiting the model.

In [25]:
from sklearn.ensemble import RandomForestClassifier

clf1 = RandomForestClassifier(n_estimators=10, random_state=33)
clf1 = clf1.fit(X_train, y_train)

measure_performance(X_test, y_test, clf1) #show_classification_report=False, show_confusion_matrix=False)

ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

In [26]:
from sklearn.neural_network import MLPClassifier

clf2 = MLPClassifier(solver='lbfgs', alpha=1e-5,
                    hidden_layer_sizes=(15), random_state=1)
clf2.fit(X_train, y_train)                         
MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto',
       beta_1=0.9, beta_2=0.999, early_stopping=False,
       epsilon=1e-08, hidden_layer_sizes=(5, 2), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='lbfgs', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)

predictions = clf2.predict(X_test)


#from sklearn.metrics import classification_report,confusion_matrix
#print(confusion_matrix(y_test,predictions))
#print(classification_report(y_test,predictions))


measure_performance(X_test, y_test, clf2) #show_classification_report=False, show_confusion_matrix=False)

Accuracy:0.265 

Classification report
             precision    recall  f1-score   support

          1       0.15      0.33      0.21      1233
          2       0.33      0.64      0.43      2486
          3       0.00      0.00      0.00      2488
          4       0.00      0.00      0.00      1293

avg / total       0.13      0.27      0.18      7500
 

Confusion matrix
[[ 405  828    0    0]
 [ 902 1584    0    0]
 [ 933 1555    0    0]
 [ 456  837    0    0]] 



/Users/SonnyDriscoll1/anaconda/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [27]:
from sklearn.svm import SVC

svc_1 = SVC(kernel='linear', C=1)
clf3 = svc_1.fit(X_train, y_train)

#To show score clf.score(X_test, y_test) 
measure_performance(X_test, y_test, clf3)  



Accuracy:0.172 

Classification report
             precision    recall  f1-score   support

          1       0.00      0.00      0.00      1233
          2       0.00      0.00      0.00      2486
          3       0.00      0.00      0.00      2488
          4       0.17      1.00      0.29      1293

avg / total       0.03      0.17      0.05      7500
 

Confusion matrix
[[   0    0    0 1233]
 [   0    0    0 2486]
 [   0    0    0 2488]
 [   0    0    0 1293]] 



/Users/SonnyDriscoll1/anaconda/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
