In [2]:
import pandas as pd
import numpy as np

df_geneData = pd.read_excel('stepDataPrep_5_6_1.xlsx', header = 0)
#skip_footer = 1000000
df_geneData.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 212527 entries, 0 to 212526
Data columns (total 7 columns):
Variable1    212527 non-null int64
Variable2    212527 non-null int64
Variable3    212527 non-null int64
Variable4    212527 non-null int64
Variable5    212527 non-null int64
Variable6    212527 non-null int64
Output       212527 non-null int64
dtypes: int64(7)
memory usage: 11.4 MB


In [3]:
df_geneDataSelect = df_geneData.head(30000)
df_geneDataSelect

Variable1  Variable2  Variable3  Variable4  Variable5  Variable6  \
0          44111      31312      23323      14424      13431      11423   
1          12333      21334      21144      42211      22132      31221   
2          34114      13141      31412      13331      13421      44444   
3          44441      11331      41311      32334      41443      24244   
4          34433      12233      44424      34341      41124      21443   
5          11322      14413      33323      33214      44222      14333   
6          11113      34434      23131      11233      43323      13324   
7          44423      14224      32323      11322      43333      14331   
8          34224      33441      42212      13332      44444      42212   
9          43223      14212      21333      14341      22222      13233   
10         12113      33441      42212      12134      42133      14312   
11         34223      42334      23322      43244      44144      11334   
12         44314      44324      43334      32423      32321      42332   
13         43433      14113      42233      22214      12332      41211   
14         13323      24424      44234      43432      23224      44221   
15         42444      33333      14142      23434      22343      31124   
16         43321      32134      32343      31424      42422      32314   
17         13243      22342      22112      11442      11212      24331   
18         22342      22443      21334      23113      22311      33231   
19         31144      32343      43414      32122      21122      34442   
20         42242      31443      33431      12313      11341      22423   
21         42322      42243      31124      32423      34311      23233   
22         31333      32114      43222      32324      44224      41441   
23         41332      13211      32321      32232      12222      32343   
24         23221      42343      22142      32114      22212      34332   
25         22222      32242      23342      32122      32232      24323   
26         23341      21322      33434      24322      32122      33423   
27         33442      24232      31131      32432      23224      34332   
28         32334      44221      32342      12332      23124      22412   
29         13323      31131      12231      32142      31422      32433   
...          ...        ...        ...        ...        ...        ...   
29970      11342      21224      23142      12242      23232      23323   
29971      24422      13332      24432      32322      43442      22131   
29972      33231      43122      31333      22333      42433      14323   
29973      43322      33423      33223      22314      22233      33314   
29974      23243      34322      23214      23333      42332      34431   
29975      31121      43232      33212      32211      13232      44322   
29976      32213      33224      23323      22432      23221      33322   
29977      33413      24232      23332      32122      42331      33224   
29978      33331      42332      12221      33324      32143      23221   
29979      13342      32232      33341      42333      14234      23323   
29980      22122      12342      31331      42422      13313      34233   
29981      21434      42234      32341      13321      22122      12342   
29982      14334      43323      42132      33221      34432      21232   
29983      22313      14212      22232      32312      33234      34133   
29984      32121      32223      44344      23123      22333      22323   
29985      22324      23122      13344      42242      33221      33223   
29986      13323      32311      32433      22323      34332      33432   
29987      33232      23443      31331      12223      13323      11333   
29988      32334      31334      13323      32344      34113      31242   
29989      22323      23322      34131      23223      23243      21432   
29990      32234      43322      14333      23321      43443      34244   
29991      22213      32131     

In [4]:
input_X = df_geneDataSelect[['Variable1','Variable2','Variable3','Variable4','Variable5','Variable6']]
output_y = df_geneDataSelect['Output']

In [5]:
from sklearn.cross_validation import train_test_split

X_train, X_test, y_train, y_test = train_test_split(input_X, output_y, test_size=0.25, random_state=33)



/Users/SonnyDriscoll1/anaconda/lib/python3.5/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [6]:
from sklearn import tree

clf = tree.DecisionTreeClassifier(criterion = 'entropy', max_depth = 8, min_samples_leaf = 2)
clf = clf.fit(X_train, y_train)

In [7]:
from sklearn import metrics

def measure_performance(X, y, clf, show_accuracy=True, show_classification_report=True, show_confusion_matrix=True):
    y_pred = clf.predict(X)
    if show_accuracy:
        print("Accuracy:{0:.3f}".format(metrics.accuracy_score(y, y_pred)),"\n")

    if show_classification_report:
        print("Classification report")
        print(metrics.classification_report(y,y_pred),"\n")

    if show_confusion_matrix:
        print("Confusion matrix")
        print(metrics.confusion_matrix(y,y_pred),"\n")
        
# And call this method for the training data (display only accuracy)
measure_performance(X_test, y_test, clf) #show_classification_report=False, show_confusion_matrix=False)




Accuracy:0.339 

Classification report
             precision    recall  f1-score   support

          1       0.27      0.07      0.12      1266
          2       0.36      0.30      0.32      2435
          3       0.34      0.66      0.45      2583
          4       0.17      0.02      0.04      1216

avg / total       0.31      0.34      0.29      7500
 

Confusion matrix
[[  94  284  846   42]
 [  84  721 1588   42]
 [ 109  722 1705   47]
 [  63  303  824   26]] 



In [8]:
from sklearn.ensemble import RandomForestClassifier

clf1 = RandomForestClassifier(n_estimators=10, random_state=33)
clf1 = clf1.fit(X_train, y_train)

measure_performance(X_test, y_test, clf1) #show_classification_report=False, show_confusion_matrix=False)

Accuracy:0.325 

Classification report
             precision    recall  f1-score   support

          1       0.21      0.20      0.20      1266
          2       0.36      0.44      0.39      2435
          3       0.37      0.37      0.37      2583
          4       0.22      0.12      0.15      1216

avg / total       0.31      0.33      0.31      7500
 

Confusion matrix
[[ 249  452  422  143]
 [ 317 1079  856  183]
 [ 365 1061  968  189]
 [ 238  442  394  142]] 



In [ ]:
from sklearn.neural_network import MLPClassifier

clf2 = MLPClassifier(solver='lbfgs', alpha=1e-5,
                    hidden_layer_sizes=(15), random_state=1)
clf2.fit(X_train, y_train)                         
MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto',
       beta_1=0.9, beta_2=0.999, early_stopping=False,
       epsilon=1e-08, hidden_layer_sizes=(5, 2), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='lbfgs', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)

predictions = clf2.predict(X_test)


#from sklearn.metrics import classification_report,confusion_matrix
#print(confusion_matrix(y_test,predictions))
#print(classification_report(y_test,predictions))


measure_performance(X_test, y_test, clf2) #show_classification_report=False, show_confusion_matrix=False)

Accuracy:0.338 

Classification report
             precision    recall  f1-score   support

          1       0.16      0.01      0.02      1266
          2       0.00      0.00      0.00      2435
          3       0.34      0.97      0.51      2583
          4       0.11      0.01      0.02      1216

avg / total       0.16      0.34      0.18      7500
 

Confusion matrix
[[  15    0 1237   14]
 [  23    0 2376   36]
 [  33    0 2511   39]
 [  22    0 1183   11]] 



/Users/SonnyDriscoll1/anaconda/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [ ]:
from sklearn.svm import SVC

svc_1 = SVC(kernel='linear', C=1)
clf3 = svc_1.fit(X_train, y_train)

#To show score clf.score(X_test, y_test) 
measure_performance(X_test, y_test, clf3)  

