In [1]:
import pandas as pd
import numpy as np

df_geneData = pd.read_excel('stepDataPrep_3_10_1.xlsx', header = 0)
#skip_footer = 1000000
df_geneData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 212527 entries, 0 to 212526
Data columns (total 11 columns):
Variable1     212527 non-null int64
Variable2     212527 non-null int64
Variable3     212527 non-null int64
Variable4     212527 non-null int64
Variable5     212527 non-null int64
Variable6     212527 non-null int64
Variable7     212527 non-null int64
Variable8     212527 non-null int64
Variable9     212527 non-null int64
Variable10    212527 non-null int64
Output        212527 non-null int64
dtypes: int64(11)
memory usage: 17.8 MB


Show header of data imported to dataframe 

In [2]:
df_geneDataSelect = df_geneData.head(30000)
df_geneDataSelect

Variable1  Variable2  Variable3  Variable4  Variable5  Variable6  \
0            441        113        131        223        323        144   
1            123        332        133        421        144        422   
2            341        141        314        131        412        133   
3            444        411        133        141        311        323   
4            344        331        223        344        424        343   
5            113        221        441        333        323        332   
6            111        133        443        423        131        112   
7            444        231        422        432        323        113   
8            342        243        344        142        212        133   
9            432        231        421        221        333        143   
10           121        133        344        142        212        121   
11           342        234        233        423        322        432   
12           443        144        432        443        334        324   
13           434        331        411        342        233        222   
14           133        232        442        444        234        434   
15           424        443        333        314        142        234   
16           433        213        213        432        343        314   
17           132        432        234        222        112        114   
18           223        422        244        321        334        231   
19           311        443        234        343        414        321   
20           422        423        144        333        431        123   
21           423        224        224        331        124        324   
22           313        333        211        443        222        323   
23           413        321        321        132        321        322   
24           232        214        234        322        142        321   
25           222        223        224        223        342        321   
26           233        412        132        233        434        243   
27           334        422        423        231        131        324   
28           323        344        422        132        342        123   
29           133        233        113        112        231        321   
...          ...        ...        ...        ...        ...        ...   
29970        113        422        122        423        142        122   
29971        244        221        333        224        432        323   
29972        332        314        312        231        333        223   
29973        433        223        342        333        223        223   
29974        232        433        432        223        214        233   
29975        311        214        323        233        212        322   
29976        322        133        322        423        323        224   
29977        334        132        423        223        332        321   
29978        333        314        233        212        221        333   
29979        133        423        223        233        341        423   
29980        221        221        234        231        331        424   
29981        214        344        223        432        341        133   
29982        143        344        332        342        132        332   
29983        223        131        421        222        232        323   
29984        321        213        222        344        344        231   
29985        223        242        312        213        344        422   
29986        133        233        231        132        433        223   
29987        332        322        344        331        331        122   
29988        323        343        133        413        323        323   
29989        223        232        332        234        131        232   
29990        322        344        332        214        333        233   
29991        222        133     

In [3]:
input_X = df_geneDataSelect[['Variable1','Variable2','Variable3','Variable4','Variable5','Variable6','Variable7','Variable8','Variable9','Variable10']]
output_y = df_geneDataSelect['Output']

Import and use train_test_split, to split data for training
(split data will be used by all algorithms)

In [4]:
from sklearn.cross_validation import train_test_split

X_train, X_test, y_train, y_test = train_test_split(input_X, output_y, test_size=0.25, random_state=33)




/Users/SonnyDriscoll1/anaconda/lib/python3.5/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


Import, fit and use Decision Tree Classifier 

In [5]:
from sklearn import tree

clf = tree.DecisionTreeClassifier(criterion = 'entropy', max_depth = 3, min_samples_leaf = 5)
clf = clf.fit(X_train, y_train)

Create function for the visualisation of metrics, and show results of Decision Tree Classifier

In [6]:
from sklearn import metrics

def measure_performance(X, y, clf, show_accuracy=True, show_classification_report=True, show_confusion_matrix=True):
    y_pred = clf.predict(X)
    if show_accuracy:
        print("Accuracy:{0:.3f}".format(metrics.accuracy_score(y, y_pred)),"\n")

    if show_classification_report:
        print("Classification report")
        print(metrics.classification_report(y,y_pred),"\n")

    if show_confusion_matrix:
        print("Confusion matrix")
        print(metrics.confusion_matrix(y,y_pred),"\n")
        
# And call this method for the training data (display only accuracy)
measure_performance(X_test, y_test, clf) #show_classification_report=False, show_confusion_matrix=False)



Accuracy:0.348 

Classification report
             precision    recall  f1-score   support

          1       0.22      0.04      0.06      1266
          2       0.31      0.23      0.26      2435
          3       0.37      0.75      0.50      2583
          4       0.21      0.06      0.09      1216

avg / total       0.30      0.35      0.28      7500
 

Confusion matrix
[[  47  360  777   82]
 [  55  554 1733   93]
 [  50  509 1941   83]
 [  65  344  739   68]] 



Create, fit and show results of Random Forest Tree Classifier

In [7]:
from sklearn.ensemble import RandomForestClassifier

clf1 = RandomForestClassifier(n_estimators=10, random_state=33)
clf1 = clf1.fit(X_train, y_train)

measure_performance(X_test, y_test, clf1) #show_classification_report=False, show_confusion_matrix=False)

Accuracy:0.340 

Classification report
             precision    recall  f1-score   support

          1       0.23      0.24      0.23      1266
          2       0.36      0.43      0.39      2435
          3       0.39      0.40      0.40      2583
          4       0.24      0.13      0.17      1216

avg / total       0.33      0.34      0.33      7500
 

Confusion matrix
[[ 299  426  394  147]
 [ 359 1052  831  193]
 [ 377  989 1039  178]
 [ 245  436  375  160]] 



Create, fit and show results of Neural Network Multi-Layer Perceptron Classifier

In [ ]:
from sklearn.neural_network import MLPClassifier

clf2 = MLPClassifier(solver='lbfgs', alpha=1e-5,
                    hidden_layer_sizes=(15), random_state=1)
clf2.fit(X_train, y_train)                         
MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto',
       beta_1=0.9, beta_2=0.999, early_stopping=False,
       epsilon=1e-08, hidden_layer_sizes=(5, 2), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='lbfgs', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)

predictions = clf2.predict(X_test)


#from sklearn.metrics import classification_report,confusion_matrix
#print(confusion_matrix(y_test,predictions))
#print(classification_report(y_test,predictions))


measure_performance(X_test, y_test, clf2) #show_classification_report=False, show_confusion_matrix=False)

Accuracy:0.321 

Classification report
             precision    recall  f1-score   support

          1       0.00      0.00      0.00      1266
          2       0.27      0.05      0.09      2435
          3       0.35      0.82      0.49      2583
          4       0.17      0.12      0.14      1216

avg / total       0.23      0.32      0.22      7500
 

Confusion matrix
[[   0  115  996  155]
 [   0  132 2036  267]
 [   0  156 2128  299]
 [   0   85  986  145]] 



/Users/SonnyDriscoll1/anaconda/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


Imports, fits and tests the Support Vector Machine classifier

In [ ]:
from sklearn.svm import SVC

svc_1 = SVC(kernel='linear', C=1)
clf3 = svc_1.fit(X_train, y_train)

#To show score clf.score(X_test, y_test) 
measure_performance(X_test, y_test, clf3)  
