In [1]:
import pandas as pd
import numpy as np

df_geneData = pd.read_excel('stepDataPrep_10_6_1.xlsx', header = 0)
#skip_footer = 1000000
df_geneData.info()

df_geneDataSelect = df_geneData.head(30000)
df_geneDataSelect









<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108005 entries, 0 to 108004
Data columns (total 7 columns):
Variable1    108005 non-null int64
Variable2    108005 non-null int64
Variable3    108005 non-null int64
Variable4    108005 non-null int64
Variable5    108005 non-null int64
Variable6    108005 non-null int64
Output       108005 non-null int64
dtypes: int64(7)
memory usage: 5.8 MB


Variable1   Variable2   Variable3   Variable4   Variable5   Variable6  \
0      4411131312  2332314424  1343111423  1123332133  4211444221  1221323122   
1      2341141314  1314121333  1134214444  4244441113  3141311323  3441443242   
2      4334433122  3344424343  4141124214  4311132214  4133332333  2144422214   
3      3321111334  4342313111  2334332313  3243444231  4224323231  1322433331   
4      3314342243  3441422121  3332444444  2212143223  1421221333  1434122222   
5      3233212113  3344142212  1213442133  1431223422  3423342332  2432444414   
6      1133424431  4443244333  4324233232  1423321434  3314113422  3322214123   
7      2412114133  2324424442  3443432232  2444221142  4443333314  1422343422   
8      4331124243  3213213432  3433142442  4223231431  3243223422  2112114421   
9      2122433142  2342224432  1334231132  2311332312  3114432343  4341432122   
10     1122344423  4224231443  3343112313  1134122423  3423224224  3311243242   
11     3431123233  2313333211  4432223232  4442244144  1141332132  1132321322   
12     2122223234  3223221423  4322142321  1422212343  3232222232  2422334232   
13     2232232243  2322334121  3223343424  3223212233  4234334422  4232311313   
14     4322322434  3323323344  4221323421  2332231242  2412313323  3113112231   
15     2142314223  2433223413  2214322332  4332322323  2233211412  3212231323   
16     1123422133  4231133232  3243113212  1221324122  4311223212  2442122442   
17     1311244234  2313332113  4221122112  4332223432  2323322433  2133433233   
18     2112242113  2143324121  1222324344  2242414334  3333423322  4333211312   
19     2122431432  1432434133  4112214243  2431131131  1422311232  2113342342   
20     1224321442  3313232442  3423233121  4334211332  2243213242  1123221421   
21     2311442113  2324424122  3242334331  2323243243  1423123141  4221344244   
22     3222341133  1323242221  3311313442  4422121224  4211232224  4242311332   
23     3221321334  3142242122  1323122324  1422311331  1142311332  4433113132   
24     3243111422  2324423324  3333224312  3343322342  3132232233  1124331112   
25     2343423231  4224314311  3113322313  2133221131  4231124322  3212314323   
26     2344244214  2322213232  1422344221  1234323231  1243311332  3232431132   
27     3343142322  2124232124  4214333423  3223142122  1423132431  4223231342   
28     2431133122  4324332224  3213312113  2433421321  4231211214  2213232122   
29     4232231341  2412113142  1131424223  1424344342  2113233234  4232344233   
...           ...         ...         ...         ...         ...         ...   
29970  2133421123  3323132333  2323313311  4132243333  3321442142  2434231133   
29971  1343222143  1321421423  4212233232  2322332442  1423321321  1424324321   
29972  3232431122  1323233231  3122312142  1423233433  1231424212  2312332313   
29973  1344223211  2243323312  3223141423  2231241224  3312213112  3124421423   
29974  1232412322  2343323124  4233422434  3232323243  4422122133  3332243232   
29975  1321222433  1113211233  3232412143  1433131121  1241223241  2132434232   
29976  4324331332  2132243311  2423323432  2344224241  2322423423  3233233424   
29977  2332322332  2331244422  3231332323  2233412313  2332232431  1234241233   
29978  4124221134  4224244231  2213232343  2322333232  4322321332  3232132213   
29979  4334233224  3232412442  1123424123  3422323231  3333212113  3332331433   
29980  2423343322  4122124324  1221321324  3232232312  3332333433  4324344233   
29981  3112143143  3244222332  2332332214  2432323124  4234232334  3313312343   
29982  2323334211  2243214442  2423122122  2321323242  3332142442  1122423321   
29983  2332232323  2321324421  1231134232  2243323343  1421121323  4423432213   
29984  3223122132  2322324334  3243323213  3232433131  3233224324  2332412232   
29985  1144222231  3323443232  3232324122  1313221412  2432322312  2433112432   
29986  4232313323  3344122323  1231444224  2134243313  3133323423  3233341243   
29987  2324332433  2323213232  24313432

In [2]:
input_X = df_geneDataSelect[['Variable1','Variable2','Variable3','Variable4','Variable5','Variable6']]
output_y = df_geneDataSelect['Output']

from sklearn.cross_validation import train_test_split

X_train, X_test, y_train, y_test = train_test_split(input_X, output_y, test_size=0.25, random_state=33)




/Users/SonnyDriscoll1/anaconda/lib/python3.5/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [3]:
from sklearn import tree

clf = tree.DecisionTreeClassifier(criterion = 'entropy', max_depth = 5, min_samples_leaf = 5)
clf = clf.fit(X_train, y_train)



In [4]:
from sklearn import metrics

def measure_performance(X, y, clf, show_accuracy=True, show_classification_report=True, show_confusion_matrix=True):
    y_pred = clf.predict(X)
    if show_accuracy:
        print("Accuracy:{0:.3f}".format(metrics.accuracy_score(y, y_pred)),"\n")

    if show_classification_report:
        print("Classification report")
        print(metrics.classification_report(y,y_pred),"\n")

    if show_confusion_matrix:
        print("Confusion matrix")
        print(metrics.confusion_matrix(y,y_pred),"\n")
        


print('Decision Tree Results:')
measure_performance(X_test, y_test, clf) #Calls measure_performance method





Decision Tree Results:
Accuracy:0.337 

Classification report
             precision    recall  f1-score   support

          1       0.00      0.00      0.00      1222
          2       0.31      0.31      0.31      2446
          3       0.35      0.68      0.47      2583
          4       0.12      0.00      0.01      1249

avg / total       0.24      0.34      0.26      7500
 

Confusion matrix
[[   0  465  749    8]
 [   0  768 1669    9]
 [   0  817 1754   12]
 [   0  461  784    4]] 



/Users/SonnyDriscoll1/anaconda/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [5]:
from sklearn.ensemble import RandomForestClassifier

clf1 = RandomForestClassifier(n_estimators=10, random_state=33)
clf1 = clf1.fit(X_train, y_train)

print('Random Forest Results:')
measure_performance(X_test, y_test, clf1) 



Random Forest Results:
Accuracy:0.314 

Classification report
             precision    recall  f1-score   support

          1       0.19      0.17      0.18      1222
          2       0.34      0.43      0.38      2446
          3       0.36      0.37      0.36      2583
          4       0.23      0.12      0.15      1249

avg / total       0.30      0.31      0.30      7500
 

Confusion matrix
[[ 213  456  421  132]
 [ 348 1042  897  159]
 [ 306 1121  954  202]
 [ 227  468  408  146]] 



In [ ]:
from sklearn.neural_network import MLPClassifier

clf2 = MLPClassifier(solver='lbfgs', alpha=1e-5,
                    hidden_layer_sizes=(15), random_state=1)
clf2.fit(X_train, y_train)                         
MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto',
       beta_1=0.9, beta_2=0.999, early_stopping=False,
       epsilon=1e-08, hidden_layer_sizes=(5, 2), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='lbfgs', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)

predictions = clf2.predict(X_test)


#from sklearn.metrics import classification_report,confusion_matrix
#print(confusion_matrix(y_test,predictions))
#print(classification_report(y_test,predictions))

print('Neural Network Results:')
measure_performance(X_test, y_test, clf2) #show_classification_report=False, show_confusion_matrix=False)





Neural Network Results:
Accuracy:0.338 

Classification report
             precision    recall  f1-score   support

          1       0.12      0.01      0.02      1222
          2       0.00      0.00      0.00      2446
          3       0.34      0.97      0.51      2583
          4       0.11      0.01      0.02      1249

avg / total       0.16      0.34      0.18      7500
 

Confusion matrix
[[  11    0 1189   22]
 [  27    0 2391   28]
 [  31    0 2515   37]
 [  19    0 1219   11]] 



/Users/SonnyDriscoll1/anaconda/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [ ]:
from sklearn.svm import SVC

svc_1 = SVC(kernel='linear', C=1)
clf3 = svc_1.fit(X_train, y_train)

print('SVM Results:')
measure_performance(X_test, y_test, clf3)  