In [ ]:
import pandas as pd
import numpy as np

df_geneData = pd.read_excel('geneData_TEST.xlsx', header = 0)
#skip_footer = 1000000
df_geneData.info()

df_geneDataSelect = df_geneData
df_geneDataSelect



In [2]:
input_X = df_geneDataSelect[['Variable1','Variable2','Variable3','Variable4','Variable5','Variable6','Variable7','Variable8','Variable9']]
output_y = df_geneDataSelect['Output']

from sklearn.cross_validation import train_test_split

X_train, X_test, y_train, y_test = train_test_split(input_X, output_y, test_size=0.25, random_state=33)




/Users/SonnyDriscoll1/anaconda/lib/python3.5/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [3]:
from sklearn import tree

clf = tree.DecisionTreeClassifier(criterion = 'entropy', max_depth = 3, min_samples_leaf = 5)
clf = clf.fit(X_train, y_train)



In [4]:
from sklearn import metrics

def measure_performance(X, y, clf, show_accuracy=True, show_classification_report=True, show_confusion_matrix=True):
    y_pred = clf.predict(X)
    if show_accuracy:
        print("Accuracy:{0:.3f}".format(metrics.accuracy_score(y, y_pred)),"\n")

    if show_classification_report:
        print("Classification report")
        print(metrics.classification_report(y,y_pred),"\n")

    if show_confusion_matrix:
        print("Confusion matrix")
        print(metrics.confusion_matrix(y,y_pred),"\n")
        


print('Decision Tree Results:')
measure_performance(X_test, y_test, clf) #Calls measure_performance method





Decision Tree Results:
Accuracy:1.000 

Classification report
             precision    recall  f1-score   support

          1       1.00      1.00      1.00        77
          2       1.00      1.00      1.00        71
          3       1.00      1.00      1.00        65
          4       1.00      1.00      1.00        75

avg / total       1.00      1.00      1.00       288
 

Confusion matrix
[[77  0  0  0]
 [ 0 71  0  0]
 [ 0  0 65  0]
 [ 0  0  0 75]] 



In [5]:
from sklearn.ensemble import RandomForestClassifier

clf1 = RandomForestClassifier(n_estimators=10, random_state=33)
clf1 = clf1.fit(X_train, y_train)

print('Random Forest Results:')
measure_performance(X_test, y_test, clf1) 



Random Forest Results:
Accuracy:1.000 

Classification report
             precision    recall  f1-score   support

          1       1.00      1.00      1.00        77
          2       1.00      1.00      1.00        71
          3       1.00      1.00      1.00        65
          4       1.00      1.00      1.00        75

avg / total       1.00      1.00      1.00       288
 

Confusion matrix
[[77  0  0  0]
 [ 0 71  0  0]
 [ 0  0 65  0]
 [ 0  0  0 75]] 



In [14]:
from sklearn.neural_network import MLPClassifier

clf2 = MLPClassifier(solver='lbfgs', alpha=1e-5,
                    hidden_layer_sizes=(15), random_state=1)
clf2.fit(X_train, y_train)                         
MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto',
       beta_1=0.9, beta_2=0.999, early_stopping=False,
       epsilon=1e-08, hidden_layer_sizes=(5, 2), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='lbfgs', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)

predictions = clf2.predict(X_test)


#from sklearn.metrics import classification_report,confusion_matrix
#print(confusion_matrix(y_test,predictions))
#print(classification_report(y_test,predictions))

print('Neural Network Results:')
measure_performance(X_test, y_test, clf2) #show_classification_report=False, show_confusion_matrix=False)





Neural Network Results:
Accuracy:1.000 

Classification report
             precision    recall  f1-score   support

          1       1.00      1.00      1.00        77
          2       1.00      1.00      1.00        71
          3       1.00      1.00      1.00        65
          4       1.00      1.00      1.00        75

avg / total       1.00      1.00      1.00       288
 

Confusion matrix
[[77  0  0  0]
 [ 0 71  0  0]
 [ 0  0 65  0]
 [ 0  0  0 75]] 



In [7]:
from sklearn.svm import SVC

svc_1 = SVC(kernel='linear', C=1)
clf3 = svc_1.fit(X_train, y_train)

print('SVM Results:')
measure_performance(X_test, y_test, clf3)  

SVM Results:
Accuracy:1.000 

Classification report
             precision    recall  f1-score   support

          1       1.00      1.00      1.00        77
          2       1.00      1.00      1.00        71
          3       1.00      1.00      1.00        65
          4       1.00      1.00      1.00        75

avg / total       1.00      1.00      1.00       288
 

Confusion matrix
[[77  0  0  0]
 [ 0 71  0  0]
 [ 0  0 65  0]
 [ 0  0  0 75]] 

