In [3]:
import pandas as pd
import numpy as np

df_geneData = pd.read_excel('stepDataPrep_30_2_1.xlsx', header = 0)
#skip_footer = 1000000
df_geneData.info()

df_geneDataSelect = df_geneData.head(30000)

input_X = df_geneDataSelect[['Variable1','Variable2']]
output_y = df_geneDataSelect['Output']

from sklearn.cross_validation import train_test_split

X_train, X_test, y_train, y_test = train_test_split(input_X, output_y, test_size=0.25, random_state=33)



from sklearn import tree

clf = tree.DecisionTreeClassifier(criterion = 'entropy', max_depth = 3, min_samples_leaf = 5)
clf = clf.fit(X_train, y_train)


from sklearn import metrics

def measure_performance(X, y, clf, show_accuracy=True, show_classification_report=True, show_confusion_matrix=True):
    y_pred = clf.predict(X)
    if show_accuracy:
        print("Accuracy:{0:.3f}".format(metrics.accuracy_score(y, y_pred)),"\n")

    if show_classification_report:
        print("Classification report")
        print(metrics.classification_report(y,y_pred),"\n")

    if show_confusion_matrix:
        print("Confusion matrix")
        print(metrics.confusion_matrix(y,y_pred),"\n")
        


print('Decision Tree Results:')
measure_performance(X_test, y_test, clf) #Calls measure_performance method


from sklearn.ensemble import RandomForestClassifier

clf1 = RandomForestClassifier(n_estimators=10, random_state=33)
clf1 = clf1.fit(X_train, y_train)

print('Random Forest Results:')
measure_performance(X_test, y_test, clf1) 


from sklearn.neural_network import MLPClassifier

clf2 = MLPClassifier(solver='lbfgs', alpha=1e-5,
                    hidden_layer_sizes=(5, 2), random_state=1)
clf2.fit(X_train, y_train)                         
MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto',
       beta_1=0.9, beta_2=0.999, early_stopping=False,
       epsilon=1e-08, hidden_layer_sizes=(5, 2), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=1, shuffle=True,
       solver='lbfgs', tol=0.0001, validation_fraction=0.1, verbose=False,
       warm_start=False)

predictions = clf2.predict(X_test)


#from sklearn.metrics import classification_report,confusion_matrix
#print(confusion_matrix(y_test,predictions))
#print(classification_report(y_test,predictions))

print('Neural Network Results:')
measure_performance(X_test, y_test, clf2) #show_classification_report=False, show_confusion_matrix=False)

from sklearn.svm import SVC

svc_1 = SVC(kernel='linear', C=1)
clf3 = svc_1.fit(X_train, y_train)

print('SVM Results:')
measure_performance(X_test, y_test, clf3)  




<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108005 entries, 0 to 108004
Data columns (total 3 columns):
Variable1    108005 non-null object
Variable2    108005 non-null object
Output       108005 non-null int64
dtypes: int64(1), object(2)
memory usage: 2.5+ MB
Decision Tree Results:
Accuracy:0.345 

Classification report
             precision    recall  f1-score   support

          1       0.00      0.00      0.00      1222
          2       0.28      0.11      0.16      2446
          3       0.35      0.90      0.51      2583
          4       0.00      0.00      0.00      1249

avg / total       0.21      0.34      0.23      7500
 

Confusion matrix
[[   0  220 1002    0]
 [   0  272 2174    0]
 [   0  269 2314    0]
 [   0  211 1038    0]] 



/Users/SonnyDriscoll1/anaconda/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


Random Forest Results:
Accuracy:0.306 

Classification report
             precision    recall  f1-score   support

          1       0.20      0.20      0.20      1222
          2       0.34      0.40      0.37      2446
          3       0.36      0.36      0.36      2583
          4       0.18      0.13      0.15      1249

avg / total       0.30      0.31      0.30      7500
 

Confusion matrix
[[239 440 380 163]
 [344 969 852 281]
 [379 992 926 286]
 [254 423 414 158]] 

Neural Network Results:
Accuracy:0.344 

Classification report
             precision    recall  f1-score   support

          1       0.00      0.00      0.00      1222
          2       0.00      0.00      0.00      2446
          3       0.34      1.00      0.51      2583
          4       0.00      0.00      0.00      1249

avg / total       0.12      0.34      0.18      7500
 

Confusion matrix
[[   0    0 1222    0]
 [   0    0 2446    0]
 [   0    0 2583    0]
 [   0    0 1249    0]] 

SVM Results:
Accuracy

/Users/SonnyDriscoll1/anaconda/lib/python3.5/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
